version: '3'

networks:
  todo-data-net:
    driver: bridge

services:

  todoapp:
    image: todoapp:3.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todoapp
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - todo-data-net
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:1.0
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql
    ports:
      - "3310:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1234
    networks:
      - todo-data-net
volumes:
  db-data:
